# path: supabase/config.toml
project_id = "pclbntueuigcsaxsixeu"

[functions.generate-app]
verify_jwt = true

[functions.github-auth]
verify_jwt = false

[functions.github-callback]
verify_jwt = false

[functions.github-push]
verify_jwt = false
