const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: authHeader } } }
    );

    const token = authHeader.replace("Bearer ", "");
    const { data: claimsData, error: claimsError } = await supabase.auth.getClaims(token);
    if (claimsError || !claimsData?.claims) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const userId = claimsData.claims.sub;

    const { project_id, repo_name } = await req.json();
    if (!project_id || !repo_name) {
      return new Response(JSON.stringify({ error: "Missing project_id or repo_name" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get GitHub token
    const adminClient = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const { data: tokenRow } = await adminClient
      .from("github_tokens")
      .select("access_token, github_username")
      .eq("user_id", userId)
      .single();

    if (!tokenRow) {
      return new Response(JSON.stringify({ error: "GitHub not connected" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Get project
    const { data: project } = await adminClient
      .from("projects")
      .select("*")
      .eq("id", project_id)
      .eq("user_id", userId)
      .single();

    if (!project) {
      return new Response(JSON.stringify({ error: "Project not found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const ghHeaders = {
      Authorization: `Bearer ${tokenRow.access_token}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    };

    // Create repo
    const repoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: ghHeaders,
      body: JSON.stringify({
        name: repo_name,
        description: `Generated by WebdevsAI: ${project.title}`,
        private: false,
        auto_init: true,
      }),
    });

    const repoData = await repoRes.json();
    if (!repoRes.ok && repoData.message !== "Repository creation failed.") {
      if (repoRes.status !== 422) {
        return new Response(JSON.stringify({ error: `GitHub: ${repoData.message}` }), {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }
    }

    const owner = tokenRow.github_username;
    const repoUrl = `https://github.com/${owner}/${repo_name}`;

    // Wait briefly for repo init
    await new Promise((r) => setTimeout(r, 2000));

    // Build files to push
    const files: Record<string, string> = {};
    const isMultipage = project.is_multipage && Array.isArray(project.pages) && project.pages.length > 0;

    if (isMultipage) {
      // Multi-page: push each page as a separate HTML file
      for (const page of project.pages) {
        const pageHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${page.title} - ${project.title}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
${page.html || ""}
</body>
</html>`;
        files[`${page.name}.html`] = pageHtml;
      }

      if (project.css) files["style.css"] = project.css;
    } else {
      // Single-page
      const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${project.title}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
${project.html || "<!-- No HTML generated -->"}
</body>
</html>`;

      files["index.html"] = indexHtml;
      if (project.css) files["style.css"] = project.css;
      if (project.react_code) files["App.jsx"] = project.react_code;
    }

    files["README.md"] = `# ${project.title}\n\nGenerated by [WebdevsAI](${Deno.env.get("SUPABASE_URL")})\n\n**Prompt:** ${project.prompt}\n\n**Type:** ${isMultipage ? "Multi-page website" : "Single-page app"}\n`;

    // Push each file via GitHub Contents API
    for (const [path, content] of Object.entries(files)) {
      let sha: string | undefined;
      try {
        const existRes = await fetch(
          `https://api.github.com/repos/${owner}/${repo_name}/contents/${path}`,
          { headers: ghHeaders }
        );
        if (existRes.ok) {
          const existData = await existRes.json();
          sha = existData.sha;
        }
      } catch {}

      const body: any = {
        message: `Add ${path}`,
        content: btoa(unescape(encodeURIComponent(content))),
      };
      if (sha) body.sha = sha;

      await fetch(
        `https://api.github.com/repos/${owner}/${repo_name}/contents/${path}`,
        { method: "PUT", headers: ghHeaders, body: JSON.stringify(body) }
      );
    }

    return new Response(JSON.stringify({ success: true, repo_url: repoUrl }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
